### ISSUE TITLE
Using pBuffer instead of pBack for blits in examples

### ISSUE THREAD

**Issue by bryanpope** [AmigaPorts/ACE#113]
At page https://github.com/AmigaPorts/ACE/blob/master/docs/programming/blit.md , the blitLine/blitRect 's are using tSimpleBufferManager->pBuffer, when I believe it should be pointing to pBack (as pBuffer does not exist)

**Comment by tehKaiN** [comment]
Yes, that's true! The tutorial is from before there was double buffering system, so I've probably forgot to update it. Will do soon!
