### ISSUE TITLE
VBR code is dangerous on CPU with data cache

### ISSUE THREAD

**Issue by rveilleux** [AmigaPorts/ACE#175]
Hi,

The code to fetch the VBR in system.c is crashing on any CPU with data cache enabled:
UWORD pGetVbrCode[] = {0x4e7a, 0x0801, 0x4e73};
This is attempting to execute code which is stored as data.
To fix it, add static const, so the compiler will place those constant into code section:
static const UWORD pGetVbrCode[] = {0x4e7a, 0x0801, 0x4e73};

(I confirmed it works on WinUAE with data cache emulation, not on a real hardware yet).

**Comment by tehKaiN** [comment]
nice find! I'll fix this soon
