### ISSUE TITLE
font_conv vector size issue

### ISSUE THREAD

**Issue by NZjeux26** [AmigaPorts/ACE#202]
When converting ttf to png, when manually adding which chars you want to use, anything above 27chars seems to hit a size limit in the vector that the inputs are stored in. See below error:
`./font_conv /home/nzjeux/local/AmigaACEPlay/amiga4ever_pro.ttf dir -out /home/nzjeux/local/AmigaACEPlay/fonts -size 8 -chars " ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.:,;"
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
Aborted (core dumped)`

**Comment by tehKaiN** [comment]
Looks like algorithm for trimming each glyph from extra left/right space was busted!
