### ISSUE TITLE
Improve mouse manager

### ISSUE THREAD

**Issue by tehKaiN** [AmigaPorts/ACE#24]
Currently, mouse actions are collected using Intuition events. Also, current cursor codebase relies on OS stuff, which is conflicting with current custom copperlist implementation. There is a need to:

- [ ] ~~Modernize API by integrating cursor into copperlist,~~
- [x] Add ability to have 2 cursors on screen (vide Settlers split-screen mode),
- [ ] ~~Display as 3bpp or 4bpp sprite with configurable sprite channel index (indices),~~
- [x] Display as the only thing on sprite channel
- [x] Display as part of sprite list for channel
- [x] Grab cursor events directly for hardware - needed in #13

**Comment by tehKaiN** [comment]
Dual mice position and 3 button states support through hardware has been implemented on branch `hardware-input`. Display is still not done.

**Comment by deuteros76** [comment]
Is there any example of how to use a mouse? 

I'm looking at Open Fire's code. I've copied cursor.c, cursor.h and cursor.bm to my project and then I included the cursorCreate, cursorUpdate and cursorDestroy calls but nothing happens. 

Maybe I missed something related to the Copper. Anyway it would be good to have an example of a mouse application in the showcase.

**Comment by tehKaiN** [comment]
Using mouse can be done with mouse manager. Displaying cursor can be done by sprite manager.

Until documentation is produced in #120, example code can be extracted from https://github.com/Last-Minute-Creations/slipgates and https://github.com/Last-Minute-Creations/openFire/ . 

Displaying 4bpp cursor will be implemented in #212.
