### ISSUE TITLE
Add TUP support

### ISSUE THREAD

**Issue by approxit** [AmigaPorts/ACE#63]
Related to #17, but more simple way, closer to makefiles.

[TUP build system docs](http://gittup.org/tup/)

**Comment by tehKaiN** [comment]
Our tupfile would need variables passed by command line https://github.com/gittup/tup/issues/355

**Comment by tehKaiN** [comment]
gittup is not that much maintained, I've got over using it, so it's gonna happen probably never. Moving to lowest priority.

**Comment by tehKaiN** [comment]
out of scope
