### ISSUE TITLE
Add MOD replayer

### ISSUE THREAD

**Issue by tehKaiN** [AmigaPorts/ACE#97]
Created as a continuation of #32 , see comments there.

I'll try to rewrite ptplayer into C so that it can be easily maintained by me and integrated into ACE across all the code refactoring we are yet to experience ;)

- [x] rewrite ptplayer to C
- [x] add OS enabling/disabling support
- [x] fix bugs on different CPU speeds
- [x] debug basic protracker commands
- [x] remove handling of audio interrupts in ACE - also when OS is enabled

**Comment by ozzyOuzo** [comment]
Maybe only adding an audio stream interface would be enough , then we could add libmikmod and an appropriate driver on top of it ? i can help :)

**Comment by tehKaiN** [comment]
The problem with ACE is that it enables/disables OS when it needs to. Most (every) libs don't support such thingy, so I think there will always be a need to do a bit more work than just writing a simple interface.

I've almost finished ptplayer rewrite, basically it needs a bit more code and tests. I would've done it already but lately I don't have time for it.

**Comment by tehKaiN** [comment]
I've added the checklist. There's a ptplayer branch for some time now, which isn't quite stable yet.

**Comment by tehKaiN** [comment]
>  remove handling of audio interrupts in ACE - also when OS is enabled

ptplayer relies on periodically checking if `INTF_AUDx` in `intreqr` register is set - basically polling for complete sample playback. I've made audio handlers which sets proper bits in dummy variable, and that works. The problem is that when sfx is done playing, the audio channel is put into endless playback loop with one word of empty data, so the interrupts trigger quite often. So there are two solutions:

- disable DMA and audio channel after the sample completed the playback,
- disable audio interrupts and go back with polling.

The first solution is problematic because I don't quite grasp the full ptplayer code, while the second one won't probably work when os is enabled, and in future os disabling will be probably optional. Dunno how to tackle it yet.
